// <auto-generated />
namespace Flex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class flexcustomertestrun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flexcustomertestrun));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231519372_flex customer test run"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
